GT_TRAIN_SET = "/storage/group/dataset_mirrors/01_incoming/3DFront/3D-FUTURE-scene/GT/train_set.json"
GT_TEST_SET = "/storage/group/dataset_mirrors/01_incoming/3DFront/3D-FUTURE-scene/GT/test_set.json"
TRAIN_SET_JSON = "train_set_processed.json"
TEST_SET_JSON = "test_set_processed.json"
SAMPLE_IMAGE = "/storage/group/dataset_mirrors/01_incoming/3DFront/3D-FUTURE-scene/test/image/0000000.jpg"
